export const englishDict = {
    "task": "Task",
    "easy": "Easy",
    "hard": "Hard",
    "run": "Run the code",
    "no": "no",
    "yes": "yes",
    "if": "if",
    "and": "and",
    "or": "or",
    "colors": {
        "blue": "blue",
        "green": "green",
        "orange": "orange",
        "red": "red",
        "purple": "purple",
        "yellow": "yellow",
        "black" : "black",
        "pink": "pink",
        "grey": "grey",
        "brown": "brown",
        "white": "white"
    },
    "general_error_message": "Invalid code, please try again",
    "ex1": {
        "title": "Task 1: Variables - Changing the Landscape",
        "description": "Welcome to the Variables Forest! Your first task is to change the landscape using <b>variables</b>. <br> Using the <b>tree color</b> variable, you can change the color of the trees.<br> Using the <b>clouds</b> variable, you can change the number of clouds.<br>Using the <b>rainbow</b> variable, you can determine whether there is a rainbow in the forest or not.",
        "trees_color": "tree color",
        "clouds": "clouds",
        "rainbow": "rainbow",
        "success": "Well done! You are welcome to continue playing with the forest variables and see it change accordingly!",
        "color_error": "The computer doesn't recognize this color.",
        "clouds_not_number": "The value of the \"clouds\" variable is invalid.",
        "clouds_error": "The computer doesn't know how to create more than 10 clouds!",
        "rainbow_error": "The possible values for the \"rainbow\" variable are \"yes\" or \"no\"",
    },
    "ex10": {
        "title": "Task 10: Conditions - Lighting Torches",
        "description": "In order to continue on your way, you need to light all the torches on the wall. Using one condition that uses <b>or</b>. <br>Each torch has three variables describing three of its properties:<b><br>color</b>: the color of the torch (green, blue, or brown)<b><br>shape</b>: the shape at the bottom of the torch (circle or triangle)<b><br>size</b>: the size of the torch (large or small)",
        "color": "color",
        "light": "light",  
        "size": "size",
        "shape": "shape",
        "small": "small",
        "large": "large",
        "circle": "circle",
        "triangle": "triangle",
        "success": "Well done, you managed to light all the torches, and now Uri and Hadas can see their way! <br>Note: You are welcome to continue playing with the code - there is more than one way to light all the torches!",
        "failure_var_doesnt_exist": "You used a variable name that doesn't exist. You should use the names \"size\", \"shape\" and \"color\".",
        "failure_wrong_color": "You used a color that doesn't exist. You should use the colors: green, blue or brown",
        "failure_wrong_size": "You used a size that doesn't exist. You should use the size \"large\" or \"small\"",
        "failure_wrong_shape": "You used a shape that doesn't exist. You should use the shapes circle or triangle",
        "wrong_answer": "The code is valid, but the condition is still not met to light all the torches, try again",
    },
};
