export const englishDict = {
    "task": "Task",
    "easy": "Easy",
    "hard": "Hard",
    "run": "Run the code",
    "no": "no",
    "yes": "yes",
    "if": "if",
    "and": "and",
    "or": "or",
    "colors": {
        "blue": "blue",
        "green": "green",
        "orange": "orange",
        "red": "red",
        "purple": "purple",
        "yellow": "yellow",
        "black" : "black",
        "pink": "pink",
        "grey": "grey",
        "brown": "brown",
        "white": "white"
    },
    "general_error_message": "Invalid code, please try again",
    "ex1": {
        "title": "Task 1: Variables - Changing the Landscape",
        "description": "Welcome to the Variables Forest! Your first task is to change the landscape using <b>variables</b>. <br> Using the <b>tree color</b> variable, you can change the color of the trees.<br> Using the <b>clouds</b> variable, you can change the number of clouds.<br>Using the <b>rainbow</b> variable, you can determine whether there is a rainbow in the forest or not.",
        "trees_color": "tree color",
        "clouds": "clouds",
        "rainbow": "rainbow",
        "success": "Well done! You are welcome to continue playing with the forest variables and see it change accordingly!",
        "color_error": "The computer doesn't recognize this color.",
        "clouds_not_number": "The value of the \"clouds\" variable is invalid.",
        "clouds_error": "The computer doesn't know how to create more than 10 clouds!",
        "rainbow_error": "The possible values for the \"rainbow\" variable are \"yes\" or \"no\"",
    },
    "ex2": {
        "title": "Task 2: Variables - The Magic Mushrooms",
        "description": "You need to fix the mushroom circle to open the secret passage in the tree and continue your journey. Each mushroom has two variables:<br>The <b>color</b> variable determines the color of the mushroom.<br>The <b>spots</b> variable determines how many spots are on the mushroom.<br>You need to put the correct values in the variables so that the mushroom correctly completes the mushroom circle!",
        "mushrooms_color": "color",
        "spots": "spots",
        "success": "Well done! This is indeed the correct mushroom, and Uri and Hadas's mushroom circle has been completed successfully!",
        "spots_error": "The computer doesn't know how to create mushrooms with more than 5 spots!",
        "spots_not_number": "The number of spots must be a number.",
        "spots_not_integer": "The number of spots must be a whole number.",
        "color_error": "The computer doesn't recognize this color.",
        "fields_error_message": "Invalid fields. Please check the fields again.",
        "failure_var_doesnt_exist": "You used a variable name that doesn't exist. You should use the names \"color\" and \"spots\".",
        "failure_var_is_missing": "You must use both the \"color\" and \"spots\" variables.",
        "wrong_answer": "The code is valid, but this is not the correct mushroom to complete the mushroom circle, try again.",
        "empty_value_error": "A variable value cannot be empty.",
        "empty_key_error": "A variable name cannot be empty.",
    },
    "ex3": {
        "title": "Task 3: Variables - Crossing the Cliff",
        "description": "To cross the cliff, we need to create a ladder of the appropriate height. We know that the height of the Biraffe is <b>3</b>, and that when combined with the ladder height, it reaches exactly the cliff height.<br>The height of the tree is stored in the <b>tree height</b> variable, so we can use it as part of the sum.",
        "ladder": "ladder",
        "biraffe": "Biraffe",
        "tree_height_variable": "tree height",
        "success": "Good work, you managed to build a ladder of the right height, and now Uri and Hadas can reach the top of the cliff!",
        "too_short_error": "The input is valid, but the ladder is too short.",
        "too_long_error": "The input is valid, but the ladder is too tall.",
        "error_tree_phrase": "You must use the \"tree height\" variable",
        "error_sign_phrase": "You must use the \"-\" or \"+\" sign",
        "error_bird_number": "You must add a number to the tree height",
        "biraffe_error": "Note: We already know that the Biraffe's height is 3, so there's no need to use the \"Biraffe\" variable - you can just write its value",
    },
    "ex4": {
        "title": "Task 4: Variables - Fixing the Bridge",
        "description": "You need to create a bridge to cross the river. We know that its length is exactly equal to the length of the first bridge plus the length of the second bridge. Variable names:<br><b>new bridge</b>: The variable that will contain the length of the complete bridge<br><b>first bridge</b>: The length of the first bridge<br><b>second bridge</b>: The length of the second bridge",
        "first_bridge": "first bridge",
        "second_bridge": "second bridge",
        "bridge_var": "new bridge",
        "success": "You managed to build the bridge, and now Uri and Hadas can cross the river!",
        "error_var_doesnt_exist": "Variable doesn't exist.",
        "error_equals_doesnt_exist": "Missing equals sign.",
        "error_no_plus_sign": "The bridge must be the sum of the two short bridges.",
        "valid_but_wrong": "The input is valid but the bridge is not the correct length",
        "empty_error": "The sum cannot be left empty",
        "empty_new_bridge_error": "Missing the \"new bridge\" variable",
    },
    "ex5": {
        "title": "Task 5: Conditions - The Castle Gate",
        "description": "The opening and closing of the gate depend on the height of whoever stands in front of it. If they are at least 200 centimeters, the gate closes. And if they are the right height, the gate opens. Note that Robi's normal height is <b>100</b> centimeters.<br>You can change Robi's height using the <b>height</b> variable to see what happens to the gate in response.",
        "height": "height",
        "success_open": "Robi's height is less than 200 centimeters so the gate opens",
        "success_closed": "Robi's height is at least 200 centimeters so the gate closes",
        "success_zero_height": "Robi's height is less than 200 centimeters so the gate opens, but because his height is 0 centimeters, there is no Robi!",
        "height_error": "The height is invalid",
        "failure_var_doesnt_exist": "You used a variable name that doesn't exist. You should use the \"height\" variable",
    },
    "ex6": {
        "title": "Task 6: Conditions - Navigating the Maze",
        "description": "The mouse's code is based on <b>conditions</b>. You need to fill in its code so that each time it encounters a flag of a certain color, it knows which direction to turn.<br>The possible flag colors are <b>red</b>, <b>yellow</b>, and <b>blue</b>, and the possible directions are <b>right</b> and <b>left</b>.",
        "flag": "flag",
        "right": "right",
        "left": "left",
        "turn": "turn",
        "success": "Well done, you correctly completed the mouse's code, and it reached the key!",
        "missing_fields_error": "All fields must be filled in.",
        "failure_wrong_color": "One of the colors you used is invalid",
        "failure_wrong_direction": "One of the directions you used doesn't exist, you should use \"right\" or \"left\"",
        "failure_two_equals_colors": "You cannot write two conditions with the same color",
        "wrong_answer": "The code is valid, but the mouse still doesn't reach the key. Try again!",
    },
    "ex7": {
        "title": "Task 7: Conditions - Fixing the Key",
        "description": "You found a blue key, but you discovered that the condition that opens the lock expects a key of a different color.<br>You need to change the <b>condition</b> so that the blue key will work and open the door. Variables:<br><b>key</b>: the color of the key.",
        "key": "key",
        "unlock_line": "door = open",
        "success": "You fixed the lock's code, and the castle door has opened!",
        "error_but_valid": "The code is valid, but the door didn't open. Please check the conditions again.",
        "error_wrong_symbol": "You used the wrong symbol instead of ==",
        "if_error": "Missing \"if\" condition",
        "key_error": "You must use the \"key\" variable",
        "color_empty_error": "Missing color for the key",
        "error_message": "Invalid fields. Please check the fields again.",
    },
    "ex8": {
        "title": "Task 8: Conditions - Fixing the Paintings",
        "description": "The flame in the fireplace blocks your way. According to its code, the fire will only go out if there are more than 4 crowns and fewer than 2 flowers in the paintings. You need to fix the paintings in the room so that the fire goes out. Variables:<br><b>crowns</b>: the number of crowns in the painting<br><b>flowers</b>: the number of flowers in the painting",
        "crowns": "crowns",
        "fire": "fire",
        "flowers": "flowers",
        "success": "The amounts of crowns and flowers match the fireplace's condition, and the flame has gone out!",
        "crowns_error": "The computer doesn't know how to create more than 7 crowns!",
        "flowers_error": "The computer doesn't know how to create more than 6 flowers!",
        "failure_var_doesnt_exist": "You used a variable name that doesn't exist. You should use the names \"crowns\" and \"flowers\".",
        "failure_var_is_missing": "You must use both the \"crowns\" and \"flowers\" variables.",
        "wrong_answer": "The code is valid but the condition is not met for the fireplace's fire to go out, try again",
    },
    "ex9": {
        "title": "Task 9: Conditions - Fixing the Fireplace",
        "description": "Once again, the flame in the fireplace blocks your way. Above it hang two paintings, with swords and stars. Unlike last time, this time you need to change the <b>fireplace</b>'s code according to the paintings, so that the fire goes out. Variables:<br><b>swords</b>: the number of swords in the painting<br><b>stars</b>: the number of stars in the painting<br><b>fire</b>: whether the fire is lit or not",
        "swords": "swords",
        "stars": "stars",
        "fire": "fire",  
        "success": "You changed the fireplace's code according to the amounts of swords and stars, and the flame has gone out!",
        "failure_var_doesnt_exist": "You used a variable name that doesn't exist. You should use the names \"stars\" and \"swords\".",
        "failure_var_is_missing": "You must use both the \"stars\" and \"crowns\" variables.",
        "wrong_answer": "The condition is still not met for the fireplace to go out, try again",
        "failure_single_condition": "You must use two conditions, one for swords and one for stars, because the goal is to practice the \"and\" principle.",
    },
    "ex10": {
        "title": "Task 10: Conditions - Lighting Torches",
        "description": "In order to continue on your way, you need to light all the torches on the wall. Using one condition that uses <b>or</b>. <br>Each torch has three variables describing three of its properties:<b><br>color</b>: the color of the torch (green, blue, or brown)<b><br>shape</b>: the shape at the bottom of the torch (circle or triangle)<b><br>size</b>: the size of the torch (large or small)",
        "color": "color",
        "light": "light",  
        "size": "size",
        "shape": "shape",
        "small": "small",
        "large": "large",
        "circle": "circle",
        "triangle": "triangle",
        "success": "Well done, you managed to light all the torches, and now Uri and Hadas can see their way! <br>Note: You are welcome to continue playing with the code - there is more than one way to light all the torches!",
        "failure_var_doesnt_exist": "You used a variable name that doesn't exist. You should use the names \"size\", \"shape\" and \"color\".",
        "failure_wrong_color": "You used a color that doesn't exist. You should use the colors: green, blue or brown",
        "failure_wrong_size": "You used a size that doesn't exist. You should use the size \"large\" or \"small\"",
        "failure_wrong_shape": "You used a shape that doesn't exist. You should use the shapes circle or triangle",
        "wrong_answer": "The code is valid, but the condition is still not met to light all the torches, try again",
    },
    "ex11": {
        "title": "Task 11: Summary - Preparing for Takeoff Part 1",
        "description": "To prepare the hot air balloon for takeoff, the first step is to adjust the flame intensity (using the <b>flame</b> variable) so that it is above 25 and less than 50.",
        "flame": "flame",
        "success": "Well done, you adjusted the flame to the correct range!",
        "flame_value_error": "The value you set for the flame is invalid",
        "failure_var_doesnt_exist": "You used a variable name that doesn't exist. You should use the \"flame\" variable.",
        "error_too_low": "The code is valid, but the flame intensity is too low",
        "error_too_high": "The code is valid, but the flame intensity is too high",
    },
    "ex12": {
        "title": "Task 12: Summary - Preparing for Takeoff Part 2",
        "description": "For the hot air balloon to be able to take off, we need to detach all sandbags that are heavier than 45 kilograms.</br>The weight of a bag is stored in the <b>weight</b> variable.",
        "weight": "weight",
        "detach": "detach = yes",
        "ifError": "Missing \"if\" condition",
        "error_message": "Invalid fields. Please check the fields again.",
        "weightWordError": "Missing \"weight\" variable",
        "signError": "Pay attention to what exactly is required in the exercise, and which sign you should use",
        "weightError": "The weight is invalid",
        "weightLimitTooLowError": "The weight you set is too low",
        "weightLimitTooHighError": "The weight you set is too high",
        "success": "Well done, you detached the correct sandbags from the hot air balloon!",
    },
    "ex13": {
        "title": "Task 13: Conditions - Preparing for Takeoff Part 3",
        "description": "On the control panel there are lights of different colors. To prepare the hot air balloon for takeoff, you need to light only the green and blue lights.<br>The light color is stored in the <b>color</b> variable.<br>The <b>light</b> variable determines whether the light is on or not.",
        "color": "color",
        "light": "light",  
        "success": "Well done, you managed to light the correct lights on the hot air balloon's control panel!",
        "failure_cond_var_doesnt_exist": "You used a variable name that doesn't exist. You should use the \"color\" variable.",
        "failure_wrong_color": "This color doesn't exist",
        "failure_action_var_doesnt_exist": "You used a variable name that doesn't exist. You should use the \"light\" variable.",
        "failure_wrong_action_val": "The value of the light variable can only be \"yes\" or \"no\".",
        "failure_no_condition": "The condition must start with the word \"if\"",
        "failure_action_no": "Although \"no\" is a valid value for the \"light\" variable, in this exercise the goal is to light the lights, not turn them off.",
        "wrong_answer": "The code is valid, but the condition is still not met to light the desired lights, try again",
    },
};
